CREATE DATABASE SURVEY_ZONE;

CREATE TABLE IF NOT EXISTS T_SURVEY(
    idx int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    item Text NOT NULL,
);

INSERT INTO T_SURVEY(item) VALUES('This is Test JSON');

SELECT * FROM T_SURVEY;